"""change data type of completed column in tasks table

Revision ID: 43541a38aec8
Revises: 7b1832f8e67a
Create Date: 2023-08-22 11:05:42.261834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43541a38aec8'
down_revision: Union[str, None] = '7b1832f8e67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
